server:
  port: 6003
dubbo:
  application:
    name: dubbo-provider
  protocol:
    port: 20881
    serialization: fastjson
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.dfs.loong.client